#!/bin/bash
# ============================================================
# Houston Build System
# Assembles agent-specific instruction files from .houston/ sources.
#
# Marker mode: If a file already exists, only the content between
# <!-- HOUSTON:START --> and <!-- HOUSTON:END --> markers is replaced.
# User-written content outside the markers is preserved.
#
# If the file does not exist, it is created with Houston content only.
#
# Usage: .houston/build.sh
# ============================================================

set -e

HOUSTON_DIR="$(cd "$(dirname "$0")" && pwd)"
WORKSPACE_DIR="$(dirname "$HOUSTON_DIR")"

# --- Load adapter list from config ---
CONFIG="$HOUSTON_DIR/config.yaml"
if [ -f "$CONFIG" ]; then
  ADAPTERS=()
  if command -v yq &>/dev/null; then
    # yq available — safe YAML parsing
    mapfile -t ADAPTERS < <(yq -r '.adapters[]' "$CONFIG" 2>/dev/null)
  fi
  # Fallback: bash parsing (when yq unavailable or yq returned nothing)
  if [ ${#ADAPTERS[@]} -eq 0 ]; then
    in_adapters=false
    while IFS= read -r line; do
      # Detect start of adapters: section
      if echo "$line" | grep -q '^adapters:'; then
        in_adapters=true
        continue
      fi
      # Stop at next top-level key
      if $in_adapters && echo "$line" | grep -q '^[a-z]'; then
        break
      fi
      # Extract "  - path/to/file" entries
      if $in_adapters; then
        path=$(echo "$line" | sed -n 's/^  *- *//p')
        [ -n "$path" ] && ADAPTERS+=("$path")
      fi
    done < "$CONFIG"
  fi
else
  # Fallback: default adapter list (no config.yaml)
  ADAPTERS=(
    "CLAUDE.md"
    ".cursorrules"
    ".windsurfrules"
    ".github/copilot-instructions.md"
  )
fi

# --- Load source files ---
IDENTITY=$(cat "$HOUSTON_DIR/IDENTITY.md")
RULES=$(cat "$HOUSTON_DIR/RULES.md")
PROCESSES=$(cat "$HOUSTON_DIR/PROCESSES.md")
CHECKLIST=$(cat "$HOUSTON_DIR/CHECKLIST.md")

# --- Assemble Houston block ---
HOUSTON_BLOCK="<!-- HOUSTON:START — Auto-generated by .houston/build.sh. DO NOT EDIT between markers. -->

${IDENTITY}

---

${RULES}

---

${PROCESSES}

---

${CHECKLIST}

<!-- HOUSTON:END -->"

# --- Write function: marker-aware ---
write_adapter() {
  local FILE="$1"

  if [ -f "$FILE" ]; then
    # File exists — check for markers
    if grep -q "<!-- HOUSTON:START" "$FILE" 2>/dev/null; then
      # Replace content between markers (inclusive)
      local TEMP=$(mktemp)
      awk '
        /<!-- HOUSTON:START/ { skip=1; print "___HOUSTON_PLACEHOLDER___"; next }
        /<!-- HOUSTON:END/   { skip=0; next }
        !skip { print }
      ' "$FILE" > "$TEMP"

      # Replace placeholder with new Houston block
      local BLOCK_TEMP=$(mktemp)
      printf '%s\n' "$HOUSTON_BLOCK" > "$BLOCK_TEMP"

      # Build final file: lines before placeholder, Houston block, lines after
      local FINAL_TEMP=$(mktemp)
      while IFS= read -r line; do
        if [ "$line" = "___HOUSTON_PLACEHOLDER___" ]; then
          cat "$BLOCK_TEMP"
        else
          printf '%s\n' "$line"
        fi
      done < "$TEMP" > "$FINAL_TEMP"

      mv "$FINAL_TEMP" "$FILE"
      rm -f "$TEMP" "$BLOCK_TEMP"
      echo "  ✅ $(basename "$FILE") (updated — user content preserved)"
    else
      # File exists but no markers — append Houston block at the end
      printf '\n%s\n' "$HOUSTON_BLOCK" >> "$FILE"
      echo "  ✅ $(basename "$FILE") (appended — existing content preserved)"
    fi
  else
    # File does not exist — create with Houston content only
    mkdir -p "$(dirname "$FILE")"
    printf '%s\n' "$HOUSTON_BLOCK" > "$FILE"
    echo "  ✅ $(basename "$FILE") (created)"
  fi
}

# --- Generate adapters ---
echo "Houston build system:"
for adapter in "${ADAPTERS[@]}"; do
  write_adapter "$WORKSPACE_DIR/$adapter"
done
echo ""
echo "Build complete. ${#ADAPTERS[@]} adapters generated."
