#!/bin/bash
# ============================================================
# houston-lib.sh — Houston Common Function Library
#
# Shared functions used by all Houston scripts.
# Source this file at the top of each script:
#
#   SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
#   source "$SCRIPT_DIR/houston-lib.sh"
#
# Provided functions:
#   find_houston_root()   — Find Houston workspace root by walking up
#   resolve_script_dir()  — Resolve symlinks to find real script dir
#   fleet_lookup()        — Lookup path/branch by project CODE
#   fleet_info()          — Print full project info by CODE
#   fleet_parse_all()     — Iterate all fleet entries (callback pattern)
#   fleet_get_hook()      — Get hook path for a project code
#   run_hook()            — Execute a lifecycle hook (non-blocking)
#   is_worktree()         — Check if a path is a git worktree
#   get_worktree_main()   — Get the main repo path for a worktree
# ============================================================

# --- find_houston_root() ---
# Walk up from $PWD to find the directory containing .houston/
# Sets HOUSTON_ROOT on success. Returns 1 on failure.
find_houston_root() {
  local dir="$PWD"
  while [ "$dir" != "/" ]; do
    if [ -d "$dir/.houston" ]; then
      echo "$dir"
      return 0
    fi
    dir=$(dirname "$dir")
  done
  return 1
}

# --- houston_find_ticket_file() ---
# Resolve a ticket id to its ticket file using the same tickets/<id>*.md
# convention as houston-resume.sh.
# Args: $1 = HOUSTON_ROOT, $2 = TICKET_ID
houston_find_ticket_file() {
  local root="$1"
  local ticket_id="$2"
  local f
  for f in "$root/tickets/"*"${ticket_id}"*".md"; do
    if [ -f "$f" ]; then
      echo "$f"
      return 0
    fi
  done
  return 1
}

# --- houston_ticket_project_code() ---
# Infer the fleet project code from a ticket id by longest prefix match:
# T-XX-MTH-123 -> XX-MTH, T-YY-1700 -> YY.
# Requires HOUSTON_ROOT to be set.
houston_ticket_project_code() {
  local ticket_id="$1"
  local fleet_file="$HOUSTON_ROOT/.houston/fleet.yaml"
  local best="" code=""

  [ -f "$fleet_file" ] || return 1
  while IFS= read -r code; do
    [ -n "$code" ] || continue
    if [[ "$ticket_id" == "T-${code}-"* ]]; then
      if [ "${#code}" -gt "${#best}" ]; then
        best="$code"
      fi
    fi
  done < <(sed -n 's/^[[:space:]]*-[[:space:]]*code:[[:space:]]*//p' "$fleet_file")

  [ -n "$best" ] || return 1
  echo "$best"
}

# --- houston_resume_base_ref() ---
# Echo "<repo-relpath> <base-branch> <origin/base oid>" when the ticket's
# fleet repo/base ref is locally resolvable. Does not fetch.
# Requires HOUSTON_ROOT to be set.
houston_resume_base_ref() {
  local ticket_id="$1"
  local code repo_rel oid

  code=$(houston_ticket_project_code "$ticket_id") || return 1
  FLEET="$HOUSTON_ROOT/.houston/fleet.yaml"
  fleet_lookup "$code" >/dev/null 2>&1 || return 1
  [ -n "$FLEET_PATH" ] && [ -n "$FLEET_BRANCH" ] || return 1
  repo_rel="${FLEET_PATH#$HOUSTON_ROOT/}"
  oid=$(git -C "$FLEET_PATH" rev-parse "origin/$FLEET_BRANCH" 2>/dev/null) || return 1
  echo "$repo_rel $FLEET_BRANCH $oid"
}

# --- houston_write_resume_context() ---
# Write the generated resume context file with deterministic freshness metadata.
# Args: $1 = context path, $2 = ticket id, $3 = resume scan body
houston_write_resume_context() {
  local context_file="$1"
  local ticket_id="$2"
  local resume_output="$3"
  local generated_at generated_minute ticket_file ticket_rel source_inputs base_ref

  generated_at=$(date '+%Y-%m-%dT%H:%M:%S%z')
  generated_minute=$(date '+%Y-%m-%d %H:%M')
  ticket_file=$(houston_find_ticket_file "$HOUSTON_ROOT" "$ticket_id" 2>/dev/null || true)
  ticket_rel="${ticket_file#$HOUSTON_ROOT/}"
  [ -n "$ticket_file" ] || ticket_rel="tickets/*${ticket_id}*.md"
  source_inputs="${ticket_rel}, tasks/CHANGESETS.md"
  base_ref=$(houston_resume_base_ref "$ticket_id" 2>/dev/null || true)

  {
    echo "# Houston Resume Context — ${ticket_id}"
    echo "# Auto-generated by \`houston work\`. Read this at session start."
    echo "# Generated: ${generated_minute}"
    echo "# Generated-At: ${generated_at}"
    echo "# Ticket-ID: ${ticket_id}"
    echo "# Source-Inputs: ${source_inputs}"
    if [ -n "$base_ref" ]; then
      echo "# Base-Ref: ${base_ref}"
    fi
    echo ""
    printf '%s\n' "$resume_output"
    echo ""
    echo "## Instructions"
    echo ""
    echo "이 티켓 작업을 이어서 진행해줘."
    echo "위의 resume scan 결과를 참고해서, 다음 미완료 IP부터 작업을 시작해."
  } > "$context_file"
}

# --- resolve_script_dir() ---
# Resolve symlinks for a given script path ($1) and echo the real directory.
# Usage: SCRIPT_DIR=$(resolve_script_dir "$0")
resolve_script_dir() {
  local source="$1"
  local dir
  while [ -L "$source" ]; do
    dir="$(cd "$(dirname "$source")" && pwd)"
    source="$(readlink "$source")"
    [[ "$source" != /* ]] && source="$dir/$source"
  done
  echo "$(cd "$(dirname "$source")" && pwd)"
}

# --- fleet_lookup() ---
# Reads fleet.yaml for a given project CODE.
# Sets FLEET_PATH (absolute) and FLEET_BRANCH.
# Requires HOUSTON_ROOT and FLEET to be set.
fleet_lookup() {
  local code="$1"

  if [ ! -f "$FLEET" ]; then
    echo "❌ Fleet manifest not found: $FLEET" >&2
    return 1
  fi

  FLEET_PATH=""
  FLEET_BRANCH=""
  FLEET_ISSUE_REPO=""
  local found=false
  while IFS= read -r line; do
    if echo "$line" | grep -q "code: $code\$"; then
      found=true
      continue
    fi
    if $found; then
      if echo "$line" | grep -q "^  - code:"; then
        break
      fi
      # NOTE: *issue_repo:* MUST be before *repo:* (if added) to avoid substring match
      case "$line" in
        *issue_repo:*) FLEET_ISSUE_REPO=$(echo "$line" | sed 's/.*issue_repo: *//');;
        *path:*)       FLEET_PATH=$(echo "$line" | sed 's/.*path: *//')       ;;
        *branch:*)     FLEET_BRANCH=$(echo "$line" | sed 's/.*branch: *//')   ;;
      esac
    fi
  done < "$FLEET"

  if [ -z "$FLEET_PATH" ]; then
    echo "❌ Project code '$code' not found in fleet.yaml" >&2
    return 1
  fi

  # Resolve to absolute path relative to Houston root
  FLEET_PATH="$HOUSTON_ROOT/$FLEET_PATH"
  return 0
}

# --- fleet_info() ---
# Print full project info for a given CODE.
# Requires FLEET to be set.
fleet_info() {
  local code="$1"

  if [ ! -f "$FLEET" ]; then
    echo "❌ Fleet manifest not found: $FLEET" >&2
    return 1
  fi

  local found=false
  local name="" repo="" path="" branch="" stack="" has_claude_md="" issue_repo=""

  while IFS= read -r line; do
    if echo "$line" | grep -q "code: $code\$"; then
      found=true
      continue
    fi
    if $found; then
      if echo "$line" | grep -q "^  - code:"; then
        break
      fi
      case "$line" in
        *issue_repo:*)    issue_repo=$(echo "$line" | sed 's/.*issue_repo: *//');;
        *name:*)          name=$(echo "$line" | sed 's/.*name: *//')          ;;
        *repo:*)          repo=$(echo "$line" | sed 's/.*repo: *//')          ;;
        *path:*)          path=$(echo "$line" | sed 's/.*path: *//')          ;;
        *branch:*)        branch=$(echo "$line" | sed 's/.*branch: *//')      ;;
        *stack:*)         stack=$(echo "$line" | sed 's/.*stack: *//')        ;;
        *has_claude_md:*) has_claude_md=$(echo "$line" | sed 's/.*has_claude_md: *//');;
      esac
    fi
  done < "$FLEET"

  if ! $found; then
    echo "❌ Project code '$code' not found in fleet.yaml" >&2
    return 1
  fi

  local claude_icon="❌"
  [ "$has_claude_md" = "true" ] && claude_icon="✅"

  echo "📡 $name ($code)"
  echo "   Repo:      $repo"
  echo "   Path:      $path"
  echo "   Stack:     $stack"
  echo "   Branch:    $branch"
  echo "   CLAUDE.md: $claude_icon"
  [ -n "$issue_repo" ] && echo "   Issues:    $issue_repo"
}

# --- fleet_parse_all() ---
# Iterate all fleet entries and extract project information.
# Populates arrays: PROJECT_DIRS (unique parent dirs),
#   FLEET_CODES, FLEET_ISSUE_REPOS (parallel arrays per entry).
# Requires FLEET to be set.
fleet_parse_all() {
  PROJECT_DIRS=()
  FLEET_CODES=()
  FLEET_ISSUE_REPOS=()
  if [ ! -f "$FLEET" ]; then
    return 1
  fi
  local current_code="" current_issue_repo=""
  while IFS= read -r line; do
    # Detect new entry
    local code
    code=$(echo "$line" | sed -n 's/.*code: *//p')
    if [ -n "$code" ]; then
      # Finalize previous entry
      if [ -n "$current_code" ]; then
        FLEET_CODES+=("$current_code")
        FLEET_ISSUE_REPOS+=("$current_issue_repo")
      fi
      current_code="$code"
      current_issue_repo=""
      continue
    fi
    # Parse fields
    local path
    path=$(echo "$line" | sed -n 's/.*path: *//p')
    if [ -n "$path" ]; then
      local parent
      parent=$(dirname "$path")
      local local_found=false
      for existing in "${PROJECT_DIRS[@]}"; do
        [ "$existing" = "$parent" ] && local_found=true && break
      done
      $local_found || PROJECT_DIRS+=("$parent")
    fi
    local ir
    ir=$(echo "$line" | sed -n 's/.*issue_repo: *//p')
    [ -n "$ir" ] && current_issue_repo="$ir"
  done < "$FLEET"
  # Finalize last entry
  if [ -n "$current_code" ]; then
    FLEET_CODES+=("$current_code")
    FLEET_ISSUE_REPOS+=("$current_issue_repo")
  fi
}

# --- fleet_get_hook() ---
# Get the hook script path for a given hook name and project code.
# Priority: fleet.yaml per-project hook > config.yaml global hook
# Args: $1 = hook_name (e.g., "on_ticket_start"), $2 = project_code (optional)
# Requires HOUSTON_ROOT to be set.
# Echoes the resolved absolute path if found, or empty string.
fleet_get_hook() {
  local hook_name="$1"
  local project_code="${2:-}"
  local hook_path=""

  local fleet_file="$HOUSTON_ROOT/.houston/fleet.yaml"
  local config_file="$HOUSTON_ROOT/.houston/config.yaml"

  # 1. Check fleet.yaml for per-project hook override
  if [ -n "$project_code" ] && [ -f "$fleet_file" ]; then
    local in_project=false
    local in_hooks=false
    while IFS= read -r line; do
      if echo "$line" | grep -q "code: ${project_code}\$"; then
        in_project=true
        continue
      fi
      if $in_project; then
        if echo "$line" | grep -q "^  - code:"; then
          break
        fi
        if echo "$line" | grep -q "hooks:"; then
          in_hooks=true
          continue
        fi
        if $in_hooks; then
          # Stop at next non-indented field
          if echo "$line" | grep -qE "^    [a-z]"; then
            local key val
            key=$(echo "$line" | sed 's/^ *//' | cut -d: -f1)
            val=$(echo "$line" | sed 's/^[^:]*: *//' | sed 's/^ *//;s/ *$//' | tr -d '"')
            if [ "$key" = "$hook_name" ] && [ -n "$val" ]; then
              hook_path="$val"
              break
            fi
          else
            in_hooks=false
          fi
        fi
      fi
    done < "$fleet_file"
  fi

  # 2. Fallback to config.yaml global hook
  if [ -z "$hook_path" ] && [ -f "$config_file" ]; then
    local in_hooks_section=false
    while IFS= read -r line; do
      # Detect lifecycle_hooks: section (top-level)
      if echo "$line" | grep -qE '^lifecycle_hooks:'; then
        in_hooks_section=true
        continue
      fi
      if $in_hooks_section; then
        # Stop at next top-level key
        if echo "$line" | grep -qE '^[a-z]'; then
          break
        fi
        local key val
        key=$(echo "$line" | sed 's/^ *//' | cut -d: -f1)
        val=$(echo "$line" | sed 's/^[^:]*: *//' | sed 's/^ *//;s/ *$//' | tr -d '"')
        if [ "$key" = "$hook_name" ] && [ -n "$val" ]; then
          hook_path="$val"
          break
        fi
      fi
    done < "$config_file"
  fi

  # Resolve to absolute path
  if [ -n "$hook_path" ]; then
    if [[ "$hook_path" != /* ]]; then
      hook_path="$HOUSTON_ROOT/$hook_path"
    fi
    echo "$hook_path"
  fi
}

# --- run_hook() ---
# Execute a lifecycle hook. Non-blocking: if the hook fails, print warning
# and continue. If the hook doesn't exist, silently skip.
#
# Args: $1 = hook_name, $2 = project_code (optional)
# Environment variables passed to hook:
#   TICKET_ID, WORKSPACE_PATH, PROJECT_CODE, BRANCH_NAME, HOUSTON_ROOT
run_hook() {
  local hook_name="$1"
  local project_code="${2:-}"

  local hook_path
  hook_path=$(fleet_get_hook "$hook_name" "$project_code")

  # No hook configured — silently skip
  if [ -z "$hook_path" ]; then
    return 0
  fi

  # Hook file doesn't exist — silently skip
  if [ ! -f "$hook_path" ]; then
    return 0
  fi

  # Hook not executable — warn and skip
  if [ ! -x "$hook_path" ]; then
    echo "⚠️  Hook not executable: $hook_path (skipping)" >&2
    return 0
  fi

  echo "🔧 Running hook: $hook_name → $(basename "$hook_path")"

  # Export context for the hook
  export HOUSTON_ROOT
  export TICKET_ID="${TICKET_ID:-}"
  export WORKSPACE_PATH="${WORKSPACE_PATH:-}"
  export PROJECT_CODE="${PROJECT_CODE:-$project_code}"
  export BRANCH_NAME="${BRANCH_NAME:-}"

  # Execute — non-blocking (warning on failure)
  if ! "$hook_path"; then
    echo "⚠️  Hook '$hook_name' failed (non-blocking, continuing)" >&2
  fi

  return 0
}

# --- is_worktree() ---
# Check if a given path is a git worktree (not a full clone).
# Worktrees have a .git FILE (not directory) pointing to the main repo.
# Returns 0 if worktree, 1 if not.
is_worktree() {
  local path="$1"
  [ -f "$path/.git" ] && return 0
  return 1
}

# --- get_worktree_main() ---
# Get the main repository path for a worktree.
# Echoes the absolute path to the main repo's working directory.
# Returns 1 if the path is not a worktree.
get_worktree_main() {
  local path="$1"
  if ! is_worktree "$path"; then
    return 1
  fi
  # git rev-parse --git-common-dir returns the shared .git dir
  local common_dir
  common_dir=$(git -C "$path" rev-parse --git-common-dir 2>/dev/null) || return 1
  # Resolve to absolute path, then get parent (working dir)
  local abs_git_dir
  abs_git_dir=$(cd "$path" && cd "$common_dir" && pwd)
  # The main repo is the parent of the .git directory
  echo "$(dirname "$abs_git_dir")"
}

# ============================================================
# Mission-tree birth-form helpers (T-HOU-022)
#
# Single source of truth for the role→glyph mapping and the canonical mission-
# tree window-name format, shared by:
#   - scripts/houston-orbit.sh        (tree renderer — STDOUT glyphs)
#   - scripts/houston-tmux-safe-launch.sh / scripts/launch-leaf-worker.sh
#                                     (launch-time birth-form — tmux window names)
# Defining the mapping once here removes the duplicate awk role_emoji() that
# used to live inside houston-orbit.sh.
# ============================================================

# --- houston_role_emoji() ---
# Canonical role/name → glyph for STDOUT rendering (houston-orbit.sh tree).
# Name-based glyphs pre-empt the archetype role (RFC-HOU-TREE-UNLIMITED-001):
# an apex / dock / hotfix node keeps its name glyph regardless of self_role.
# May return a multi-codepoint grapheme (ZWJ 🧑‍🚀 / VS16 🛰️ ✈️ 🛏️) — that is
# fine for a terminal stdout tree, but NOT for tmux window names (see
# houston_role_emoji_tmux below).
# Args: $1 = session name, $2 = self_role.  Echoes one glyph (no newline).
houston_role_emoji() {
  local sess="$1" role="$2"
  local dock_re='(^|[-_])dock'
  local hf_re='hotfix|(^|[-_])hf[0-9]?([-_]|$)'
  # Name-based glyphs first (pre-empt archetype).
  if [[ "$sess" == "houston" ]]; then printf '🛰️'; return; fi
  if [[ "$sess" =~ $dock_re ]]; then printf '🛏️'; return; fi
  if [[ "$sess" =~ $hf_re ]]; then printf '🚑'; return; fi
  # Archetype glyphs.
  case "$role" in
    mission_control) printf '🛰️' ;;
    crew)            printf '🧑‍🚀' ;;
    probe)           printf '🔬' ;;
    flight)          printf '✈️' ;;   # Crew-class alias (transition)
    flight_deck)     printf '🚀' ;;   # Crew-class alias (transition)
    *)               printf '🚀' ;;   # default (legacy mission/program/unknown)
  esac
}

# --- houston_role_emoji_tmux() ---
# tmux-SAFE window-name glyph variant. tmux's status-line width calculation
# mis-measures multi-codepoint grapheme clusters: a ZWJ sequence
# (🧑‍🚀 = U+1F9D1 U+200D U+1F680) is counted wider than the terminal renders it,
# which corrupts the status bar (MC empirical finding 2026-06-06: a 🧑‍🚀 window
# name duplicated the status bar 8×). Window-name glyphs therefore MUST be
# single Unicode scalars with NO ZWJ (U+200D) and NO variation selector
# (U+FE0F). This wraps houston_role_emoji() — keeping the name/role logic in ONE
# place — and substitutes only the multi-codepoint glyphs with single-scalar,
# emoji-presentation-default equivalents:
#   🧑‍🚀 (ZWJ)  → 🚀   crew / Crew-class
#   🛰️ (VS16)  → 📡   mission_control / houston (apex)
#   🛏️ (VS16)  → 💤   dock (parked / idle)
#   ✈️ (VS16)  → 🛫   flight (alias)
# Single-scalar glyphs (🔬 probe, 🚑 hotfix, 🚀 flight_deck/default) pass through.
# Args: $1 = session name, $2 = self_role.  Echoes one single-scalar glyph.
houston_role_emoji_tmux() {
  local glyph; glyph="$(houston_role_emoji "$1" "$2")"
  case "$glyph" in
    '🧑‍🚀') printf '🚀' ;;
    '🛰️')  printf '📡' ;;
    '🛏️')  printf '💤' ;;
    '✈️')  printf '🛫' ;;
    *)       printf '%s' "$glyph" ;;
  esac
}

# --- houston_window_name() ---
# Compose the canonical mission-tree window name: "<glyph> <objective>".
# The objective (identifier) is sanitized to a single line — any run of
# whitespace (space / tab / newline) collapses to one space and leading/
# trailing whitespace is trimmed. The designation coordinate (1.2.1 …) is
# NEVER part of the name (render-time only — no-drift invariant,
# RFC-HOU-TREE-UNLIMITED-001).
# Args: $1 = glyph (use houston_role_emoji_tmux for tmux window names),
#       $2 = objective / identifier.
houston_window_name() {
  local glyph="$1" objective="$2" clean
  clean="$(printf '%s' "$objective" | tr '\n\t\r' '   ' \
            | sed -E -e 's/[[:space:]]+/ /g' -e 's/^ //' -e 's/ $//')"
  if [ -n "$clean" ]; then
    printf '%s %s' "$glyph" "$clean"
  else
    printf '%s' "$glyph"
  fi
}

# --- houston_is_role_glyph() ---
# True (exit 0) iff $1 is a recognized Houston role glyph — either the stdout
# archetype set (houston_role_emoji) OR the tmux-safe single-scalar variant
# (houston_role_emoji_tmux). Single source for "is this window a birth-formed
# node?" used by `houston-orbit.sh tree` window-child detection (T-HOU-025 G2).
houston_is_role_glyph() {
  case "$1" in
    '🛰️'|'📡'|'🧑‍🚀'|'🚀'|'🔬'|'🛏️'|'💤'|'🚑'|'✈️'|'🛫'|'🔵') return 0 ;;
    *) return 1 ;;
  esac
}

# --- houston_strip_window_coord() ---
# Remove a leading designation coordinate ("1", "1.2.1", …) plus its trailing
# whitespace from a window name, leaving "<glyph> <objective>". Idempotency seam
# for `houston-orbit.sh relabel` (T-HOU-025 G3): relabel strips any existing
# coordinate before re-applying, so re-running never doubles the prefix. Only a
# numeric dotted token followed by whitespace is stripped (a glyph or normal
# objective is left untouched).
houston_strip_window_coord() {
  printf '%s' "$1" | sed -E 's/^[0-9]+(\.[0-9]+)*[[:space:]]+//'
}
