#!/bin/bash
# ============================================================
# houston-work.sh — Launch AI agent with ticket context
#
# Runs resume scan, saves context, and launches the configured
# AI agent with the resume context as initial prompt.
#
# Usage:
#   houston-work.sh <TICKET_ID>
#
# Agent is configured in .houston/config.yaml:
#   agent:
#     cli: claude    # claude | gemini
#     auto_resume: true
#
# Examples:
#   houston-work.sh T-XX-100
#   houston-work.sh T-INFRA-001
# ============================================================

set -e

# --- Load common library ---
source "$(cd "$(dirname "$0")" && pwd)/houston-lib.sh"

HOUSTON_ROOT=$(find_houston_root) || {
  echo "❌ Not inside a Houston workspace (.houston/ not found)" >&2
  exit 1
}

TICKET_ID="${1:-}"
if [ -z "$TICKET_ID" ]; then
  echo "Usage: houston work <TICKET_ID>"
  echo ""
  echo "Examples:"
  echo "  houston work T-XX-100"
  echo "  houston work T-INFRA-001"
  exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
CONFIG="$HOUSTON_ROOT/.houston/config.yaml"

# --- Read agent config ---
AGENT_CLI="claude"
AUTO_RESUME="true"

if [ -f "$CONFIG" ]; then
  # Parse agent.cli
  val=$(grep -A5 '^agent:' "$CONFIG" 2>/dev/null | grep 'cli:' | head -1 | awk '{print $2}')
  [ -n "$val" ] && AGENT_CLI="$val"

  # Parse agent.auto_resume
  val=$(grep -A5 '^agent:' "$CONFIG" 2>/dev/null | grep 'auto_resume:' | head -1 | awk '{print $2}')
  [ "$val" = "false" ] && AUTO_RESUME="false"
fi

# --- Verify agent CLI is installed ---
if ! command -v "$AGENT_CLI" &>/dev/null; then
  echo "❌ Agent CLI not found: $AGENT_CLI" >&2
  echo "   Install it or change agent.cli in .houston/config.yaml" >&2
  exit 1
fi

# --- Run resume scan ---
CONTEXT_FILE="$HOUSTON_ROOT/.houston/resume-context.md"

if [ "$AUTO_RESUME" = "true" ]; then
  echo "📡 Running resume scan for ${TICKET_ID}..."
  echo ""

  # Capture resume output
  RESUME_OUTPUT=$("$SCRIPT_DIR/houston-resume.sh" "$TICKET_ID" 2>&1) || {
    echo "❌ Resume scan failed for ${TICKET_ID}" >&2
    echo "$RESUME_OUTPUT" >&2
    exit 1
  }

  # Display resume output
  echo "$RESUME_OUTPUT"
  echo ""

  # Save context file
  cat > "$CONTEXT_FILE" << CTXEOF
# Houston Resume Context — ${TICKET_ID}
# Auto-generated by \`houston work\`. Read this at session start.
# Generated: $(date '+%Y-%m-%d %H:%M')

${RESUME_OUTPUT}

## Instructions

이 티켓 작업을 이어서 진행해줘.
위의 resume scan 결과를 참고해서, 다음 미완료 IP부터 작업을 시작해.
CTXEOF

  echo "📋 Context saved: .houston/resume-context.md"
  echo ""
fi

# --- Launch agent ---
echo "🚀 Launching ${AGENT_CLI}..."
echo ""

# Build the initial prompt
PROMPT="Houston, ${TICKET_ID} 작업을 이어서 진행해줘."

if [ "$AUTO_RESUME" = "true" ] && [ -f "$CONTEXT_FILE" ]; then
  PROMPT="$(cat "$CONTEXT_FILE")"
fi

# Agent-specific launch
cd "$HOUSTON_ROOT"

case "$AGENT_CLI" in
  claude)
    # claude "prompt" → interactive session with initial message
    exec claude "$PROMPT"
    ;;

  gemini)
    # gemini -i "prompt" → interactive mode with initial prompt
    exec gemini -i "$PROMPT"
    ;;

  *)
    # Generic fallback: try passing prompt as positional argument
    echo "⚠️  Unknown agent '$AGENT_CLI'. Attempting generic launch..."
    exec "$AGENT_CLI" "$PROMPT"
    ;;
esac
